config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resource :developers, only: [:new, :create]
  end

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:index, :show]
    end
  end

  root :to => "web/board#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :my_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  validates :first_name,length: { minimum: 2 }, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create },
            presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_url
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_url
    else
      render :new_admin_user_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :type)
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

class Api::V1::UsersController < Api::V1::ApplicationController
  def show
    user = User.find(params[:id])
    respond_with(user)
  end

  def index
    q_params = params[:q] || { s: 'id asc' }
    users = User.all
                .ransack(q_params)
                .result
    json = {
      items: users.map { |u| UserSerializer.new(u).as_json },
      meta: build_meta_users(users)
    }
    respond_with json
  end
end

app/views/admin/users/edit.html.slim
= simple_form_for [:admin, @user], as: :user, url: admin_user_url do |f|
  .row
    .col-lg-1
      = f.button :submit, "Back", formaction: admin_users_url, formmethod: "get"
    .col-lg-11
      h4  Create new user
  p
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']
  = f.button :submit, "Confirm"

app/views/admin/users/index.html.slim
h3 Users list
= link_to "Add new user", new_admin_user_path
.container
  .row
    .col-lg-10
    .col-lg-2
      = search_form_for(@q, url:admin_users_url, method: :get) do |f|
        = f.search_field :email_cont, placeholder: "Search by email"
table.table
  thead
    tr
      th= sort_link(@q, :id, "#")
      th= sort_link(@q, :first_name, "First Name")
      th= sort_link(@q, :last_name, "Last Name")
      th= sort_link(@q, :email, "Email")
      th= sort_link(@q, :type, "Type")
      th scope="col"  Actions
  tbody
    - @users.each do |user|
      tr
        td= user.id
        td= user.first_name
        td= user.last_name
        td= user.email
        td= user.type
        td
          => link_to "Edit", edit_admin_user_path(user)
          -if current_user.id != user.id
            =< link_to "Delete", admin_user_path(user), method: "delete"
= paginate @users
= page_entries_info @users

app/views/admin/users/new.html.slim
= simple_form_for @user, url: new_admin_user_path do |f|
  .row
    .col-lg-1
      = f.button :submit, "Back", formaction: admin_users_url, formmethod: "get"
    .col-lg-11
      h4  Create new user
  p
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :password
  = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']
  = f.button :submit, "Create", formaction: admin_users_path

app/views/admin/users/show.html.slim
h1 User profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span Email:&nbsp;
  strong= @user.email

= link_to "Back to index", admin_users_path